# Owner: Omar
all:
  children:
    routers:
      hosts:
        cisco_router:
          ansible_host: 192.168.1.1        # update to GNS3 router IP
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_user: "{{ vault_router_user }}"
          ansible_password: "{{ vault_router_password }}"
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: "{{ vault_router_enable }}"

    linux:
      hosts:
        linux_host:
          ansible_host: 192.168.1.100      # update to Linux host IP
          ansible_user: "{{ vault_linux_user }}"
          ansible_password: "{{ vault_linux_password }}"
          ansible_connection: ssh