# Owner: Omar
all:
  children:
    routers:
      hosts:
        cisco_router:
          ansible_host: 192.168.229.129
          ansible_network_os: cisco.ios.ios
          ansible_connection: network_cli
          ansible_user: "{{ vault_router_user }}"
          ansible_password: "{{ vault_router_password }}"
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: "{{ vault_router_password }}"
          ansible_timeout: 60

    linux:
      hosts:
        linux_host:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_user: "{{ vault_linux_user }}"
          ansible_password: "{{ vault_linux_password }}"
          ansible_connection: ssh
          ansible_host_key_checking: false
          ansible_python_interpreter: /usr/bin/python3.12
