# Owner: Ahmed Alyasin A21EC403
# To be implemented on branch: feature/linux-activity
- name: Collect Linux system information - Part 2
  hosts: linux
  gather_facts: yes
  vars_files:
    - ../vars/vault.yml

  tasks:
    - name: Get logged-in users
      command: who
      register: logged_in_users
      changed_when: false

    - name: Display logged-in users
      debug:
        msg: "{{ logged_in_users.stdout_lines }}"

    - name: Get top 5 processes by CPU usage
      shell: ps aux --sort=-%cpu | head -6 | tail -5
      register: top_processes
      changed_when: false

    - name: Display top 5 processes
      debug:
        msg: "{{ top_processes.stdout_lines }}"

    - name: Generate system info report
      template:
        src: ../templates/report.j2
        dest: ./report.md
      delegate_to: localhost