---
- name: Collect Linux system information - Part 1
  hosts: linux
  gather_facts: yes
  vars_files:
    - ../vars/vault.yml

  tasks:
    - name: Display hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Display current date and time
      debug:
        msg: "Date & Time: {{ ansible_date_time.iso8601 }}"
